// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/logout": {
            "post": {
                "tags": [
                    "认证"
                ],
                "summary": "登出",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/nonce/{addr}": {
            "get": {
                "tags": [
                    "认证"
                ],
                "summary": "获取登录 Nonce",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户addr",
                        "name": "addr",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "tags": [
                    "认证"
                ],
                "summary": "刷新 Token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/verify": {
            "post": {
                "tags": [
                    "认证"
                ],
                "summary": "SIWE 登录",
                "parameters": [
                    {
                        "description": "登录数据",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth_api.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/decorationType": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "基础数据"
                ],
                "summary": "装修类型",
                "parameters": [
                    {
                        "type": "string",
                        "description": "测试token",
                        "name": "Authorization",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/furnitureType": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "基础数据"
                ],
                "summary": "房屋设施",
                "parameters": [
                    {
                        "type": "string",
                        "description": "测试token",
                        "name": "Authorization",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/houseType": {
            "get": {
                "tags": [
                    "基础数据"
                ],
                "summary": "房源类型",
                "parameters": [
                    {
                        "type": "string",
                        "description": "测试token",
                        "name": "Authorization",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/orientationType": {
            "get": {
                "tags": [
                    "基础数据"
                ],
                "summary": "朝向",
                "parameters": [
                    {
                        "type": "string",
                        "description": "测试token",
                        "name": "Authorization",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/rentInclude": {
            "get": {
                "tags": [
                    "基础数据"
                ],
                "summary": "租金包含",
                "parameters": [
                    {
                        "type": "string",
                        "description": "测试token",
                        "name": "Authorization",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/rentPayType": {
            "get": {
                "tags": [
                    "基础数据"
                ],
                "summary": "付款方式",
                "parameters": [
                    {
                        "type": "string",
                        "description": "测试token",
                        "name": "Authorization",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/rentState": {
            "get": {
                "tags": [
                    "基础数据"
                ],
                "summary": "出租状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "测试token",
                        "name": "Authorization",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/basic/rentType": {
            "get": {
                "tags": [
                    "基础数据"
                ],
                "summary": "出租类型",
                "parameters": [
                    {
                        "type": "string",
                        "description": "测试token",
                        "name": "Authorization",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/home/info": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "登录注册"
                ],
                "summary": "当前用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "测试token",
                        "name": "Authorization",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/home/login": {
            "post": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "登录注册"
                ],
                "summary": "获取token",
                "parameters": [
                    {
                        "description": "{'username':'a1@qq.com','password':'123456'}",
                        "name": "para",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/home/logout": {
            "post": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "登录注册"
                ],
                "summary": "退出",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/house/del/{id}": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "房源"
                ],
                "summary": "删除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "测试token",
                        "name": "Authorization",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/house/info/{id}": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "房源"
                ],
                "summary": "单条数据",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "业务id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "测试token",
                        "name": "Authorization",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/house/page": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "房源"
                ],
                "summary": "分页列表",
                "parameters": [
                    {
                        "type": "string",
                        "example": "市",
                        "name": "city",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "县",
                        "name": "county",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "current",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "",
                        "name": "orderAsc",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "",
                        "name": "orderDesc",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "省",
                        "description": "Ccid uint64 ` + "`" + `json:\"ccid\" form:\"ccid\" desc:\"记录总数\" example:\"100\"` + "`" + `",
                        "name": "province",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "records",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 10,
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 100,
                        "name": "total",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "镇",
                        "name": "town",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "example": false,
                        "name": "unPage",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/house/save": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "房源"
                ],
                "summary": "保存",
                "parameters": [
                    {
                        "description": "如：{'name':'jii','id':8}",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/user/addr/{addr}": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "单条数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户addr",
                        "name": "addr",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "测试token",
                        "name": "Authorization",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/user/del/{id}": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "货品"
                ],
                "summary": "删除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "测试token",
                        "name": "Authorization",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/user/info/{id}": {
            "get": {
                "consumes": [
                    "application/x-json-stream"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "单条数据",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "测试token",
                        "name": "Authorization",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/user/page": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "用户"
                ],
                "summary": "分页列表",
                "parameters": [
                    {
                        "type": "string",
                        "example": "市",
                        "name": "city",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "县",
                        "name": "county",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 1,
                        "name": "current",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "昵称",
                        "name": "nickname",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "",
                        "name": "orderAsc",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "",
                        "name": "orderDesc",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "省",
                        "description": "Ccid uint64 ` + "`" + `json:\"ccid\" form:\"ccid\" desc:\"记录总数\" example:\"100\"` + "`" + `",
                        "name": "province",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "records",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 10,
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 100,
                        "name": "total",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "镇",
                        "name": "town",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "example": false,
                        "name": "unPage",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/user/save": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "用户"
                ],
                "summary": "保存",
                "parameters": [
                    {
                        "description": "如：{'name':'jii','id':8}",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/e.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth_api.LoginReq": {
            "type": "object",
            "required": [
                "message",
                "signature"
            ],
            "properties": {
                "message": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                }
            }
        },
        "e.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "headerl"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Gin swagger",
	Description:      "Gin swagger 示例项目",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
